[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Reflection.AssemblyProduct("Sx1232 bootloader")]
[assembly: System.Reflection.AssemblyTitle("SX1232 Baylan Bootloader Kit V1.0")]
[assembly: System.Reflection.AssemblyDescription("16.09.2019 \r\n Coşkun ERGAN")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyCompany("Semtech")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 Semtech 2011")]
[assembly: System.Runtime.InteropServices.Guid("6214011d-719f-48fa-8661-75e130ef6e00")]
[assembly: System.Reflection.AssemblyFileVersion("2.1.0.0")]

